language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "pypy"
    - "pypy3"
services:
    - postgresql
env:
    - POKEDEX_DB_ENGINE=postgresql:///pokedex
sudo: false

install: pip install -e .
before_script:
    - createdb -U postgres pokedex
    - pokedex setup -v
script: py.test
